### ISSUE TITLE
Tracking issue?

### ISSUE THREAD

**Issue by justinseesdragons** [mgazdzik/plugin-ShortcodeTracker#15]
Hi mgazdzik,

Here is my scenario:
Using img tracking pixel (no javascript)
Created shortcode for www.example.com
<a href="http://XXX.XXX.XXX.XXX/piwik/index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code=730eb0">example.com...

Result:
I see the page view
I get redirected to example.com
I dont see the event on the visit summary

What am I doing wrong?

Thanks!
justin@weseedragons.com

**Comment by mgazdzik** [comment]
Hi @justinseesdragons,

I've got a couple of questions that could possibly help resolving your issue:
- is "www.example.com" main url of Piwik site you want to perform redirect to?
- do you have "PiwikTracker" library imported into your Piwik instance ( it should sit in piwik_root/libs/PiwikTracker/ directory) ?
- are there any notifications in php error logs?

Additionally it would be really helpful if you could provide a database entry for Piwik site you want to redirect to and db row with generated shortcode.
In case you don't want to share this data publicly, please feel free to email me with those (michal.gazdzik@gmail.com).

Cheers!

update:

also a thought - have you configured your shortener URL in Plugin Settings section? This part is also quite important for sake of redirects tracking. Please check out this part of documentation for more information https://github.com/mgazdzik/plugin-ShortcodeTracker#plugin

**Comment by justinseesdragons** [comment]
Hi Michal,

To answer your questions:
1.   www.example.com is really www.example.com and is not my site.  I am
testing tracking external out links (which register when I use the Piwik
javascript tag).  Because I am using the img tag I am extremely limited in
what I can track and have no way of knowing if a user clicked an out link.
This is why I went with your plugin because I assumed that you would do two
things I needed which was registering the out link visited event in Piwik
and then redirecting to the external out link I set up with the short
code.  The redirect to www.example.com works great and shows me that your
plugin is successfully being called.  However, registering that same event
in Piwik does not seem to work (but does when I use the Piwik javascript
tag and no shortcodes)
2. Yes
3. Error in Piwik (tracker): Invalid idSite: '0'

I hope this clarifies my situation.  Thank you very much for your help!

Justin

**Comment by mgazdzik** [comment]
Hi Justin,

So if I understand well - you want to track redirects to "external" urls. This case unfortunately wasn't handled in version 0.4.5 you are probably using. Reason for this is that there is need to select a site, which would be a container for such 'external' traffic (clearly, it can't be just attributed to any site you track, as this would affect your site stats).

However - yesterday I've released version 0.5.0, which allows you to pick to which site in your Piwik instance you want to collect such external redirects.

Therefore I would suggest updating plugin to latest version, configuring a new site that will collect all those events for you (see https://github.com/mgazdzik/plugin-ShortcodeTracker#external-redirects-tracking ) and I hope this will meet your requirements.

Please let me know if this worked for you?

Cheers!

**Comment by justinseesdragons** [comment]
Hi Michal,

Wow!  Thank you for releasing 0.5.0!  I will give it a try and let you know.

Justin

**Comment by justinseesdragons** [comment]
0.5.0 WORKS GREAT!!
THANK YOU VERY MUCH!

Justin

**Comment by mgazdzik** [comment]
Great, I'm happy plugin functionality meets your needs :) 

Also please feel free to request any feature you may find useful - any feedback is appreciated :)
