### ISSUE TITLE
Create screenshots for the Marketplace

### ISSUE THREAD

**Issue by tsteur** [mgazdzik/plugin-ShortcodeTracker#21]
Hi @mgazdzik hope you're doing well!

Was just checking out your plugin and noticed there are no screenshots available on the Marketplace. By putting a screenshot inside your `screenshots` folder and releasing a new tag they should be visible on the Marketplace.

Cheers

**Comment by mgazdzik** [comment]
Screenshots have (finally ;) ) been added on occasion of https://github.com/mgazdzik/plugin-ShortcodeTracker/pull/24 

Thanks for reaching out about this :+1:

Cheers,
Michal
