### ISSUE TITLE
Desired shortcode and campaign stuff...

### ISSUE THREAD

**Issue by 9uenther** [mgazdzik/plugin-ShortcodeTracker#22]
I have extended the plugin with some custom stuff. Like a desired shortcode field and some campaign stuff. Please tell me whether makes it sense for others?!

![image](https://cloud.githubusercontent.com/assets/5249946/15866127/b1b9181c-2cdd-11e6-8625-e4fb33660a01.png)

**Comment by mgazdzik** [comment]
Hello @fhrtms ,
 Thanks for steping up with this ideas in the first place.
As for my thoughts here are some points:
- custom shortcodes - I love this idea, but restricting those to 6 digits would be irrational I think, so what could be done instead - create slightly altered ShortCode class with different (more loose) validation - for ex. it only has to be unique. Such change would also require changes in schema to distinguish which code is 'hash' and which is custom. Also do you think about integrating this also with Actions report shortcut? It might be worth adding separate datatable row icon that would allow defining custom shortcode. (this however is just a loose idea)
- campaign params - also very cool, but on screenshot provided I think it might distract user from main field - url to shorten. Therefore maybe it would be worth to introduce something like 'advanced mode' in plugin settings and then display such extended form? Idea of basic functionality is to keep things simple and minimize flow of usage to minimum. Also possibly campaign fields could be folded somehow so they're hidden by default and offering user to expand on demand. 

Additionally last but not least - from what I read in docs Piwik by default only handles campaign keyword and campaign name, while more params are handled by AdvancedCampaignReporting plugin - it mightbe also worth considering while planning this feature.

Please let me know if any of my thoughts make sense to you or if we can discuss them further?

Cheers!

**Comment by 9uenther** [comment]
Hi @mgazdzik,

for a longer "6-char" shortcode i wuold easily change the type of db "code" column from varchar(6) to varchar(24) and use a parallel validation for custom shortcodes. I tested it with some other adjustments, and it work.

For the campaign params i use the google-analytics notation (utm_source, utm_medium, etc.). 
By default we can use the keyword and campaign name, when the scripts detects the activated AdvancedCampaignReporting-Plugin we can unhide the other textfields...

Bye

**Comment by mgazdzik** [comment]
Hi @fhrtms, sorry for very long silence on my end.
Fortunately I will be able to spend more time on plugin from now, so if you're still interested in extending plugin with features you've described, please let me know and I'll try to schedule some work on my end on this thing.
Otherwise I'll just close this issue as no longer needed.

Cheers,
