### ISSUE TITLE
various Feedback

### ISSUE THREAD

**Issue by Findus23** [mgazdzik/plugin-ShortcodeTracker#28]
Hi, 
I just stumbled across your plugin again as it has a lot of potential and I guess there are many people who could use it.

But at the moment the setup is a bit hard to understand. 

I'd recommend you to change the Headings to ```###``` as otherwise only the first paragraph is shown
alternatively you can move the longer docs to `docs/`
See also 
https://developer.matomo.org/guides/distributing-your-plugin

The apache and nginx config should be renamed from `.md` as they are otherwise broken in Github. And I don't know Apache at all, but I think a closing tag is missing in the config.

Many thanks for your great plugin, I think many people would like to use it.

**Comment by mgazdzik** [comment]
Hi @Findus23 thanks for your feedback, I've made the changes you suggested. Hope this will help get along better with the plugin :)
Cheers!
Mike

**Comment by Findus23** [comment]
Hi,

Many thanks for the update.

Did you update the repo as mentioned in https://developer.matomo.org/guides/distributing-your-plugin#activate-the-piwik-plugins-webhook? (because Github removed the old way to add webhooks)

Because it doesn't seem like the plugin is updating on the marketplace:
https://plugins.matomo.org/ShortcodeTracker

**Comment by mgazdzik** [comment]
Hi, indeed I did not update the webhooks sections. 
Just fixed that and made a version bump. Hope that this will result in an automated update.

Thanks a lot for pointing that!
Cheers,
Mike

**Comment by Findus23** [comment]
And it is there!

Any reason why you reverted the headings from https://github.com/mgazdzik/plugin-ShortcodeTracker/commit/a6e37f80a52bfa27db9f29c8a7a615bacc70f854#diff-04c6e90faac2675aa89e2176d2eec7d8 in  https://github.com/mgazdzik/plugin-ShortcodeTracker/commit/f756c2d121ff3f92cf5be1d3db365640d340b95f?
Because now again the required setup isn't shown

**Comment by mgazdzik** [comment]
Yes, I reverted because in Marketplace the description went blank. After second thought (and reading docs ;) ) I figured out what formatting should be applied. it's fixed now.
