### ISSUE TITLE
Better example for Apache

### ISSUE THREAD

**Issue by TheCuriousHacker** [mgazdzik/plugin-ShortcodeTracker#29]
Below is an example of better code for Apache redirect

For example https://mystatsite.com/go/123456

On this case it's easier to separate short URL's from other URLs's. You can remove go/ to use redirect without "directory": 

```
# BEGIN Matomo Short URL
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f  
RewriteCond %{REQUEST_FILENAME} !-d
RewriteBase /
RewriteRule ^go/([a-zA-Z0-9]{6})$ /index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code=$1 [L]
</IfModule>
# END Matomo Short URL
```

**Comment by mgazdzik** [comment]
@TheCuriousHacker thanks for that hint! It took long enough but today I'm planning to make a new version release and it'll incorporate your suggestion in docs.
Cheers!
