### ISSUE TITLE
Is this plugin still supported/developed?

### ISSUE THREAD

**Issue by Makkmetp** [mgazdzik/plugin-ShortcodeTracker#30]
Hi,

First of all, thank you creating this plugin. I like it a lot. 
But I see the last commit is done more than a year ago. Is there still anyone working on this plugin? 

Regards,
Peter

**Comment by mgazdzik** [comment]
Hello @Makkmetp,
 Thank you very much for your kind words, awesome to hear that plugin still does it's job.
As for your question it isn't developed actively, as there isn't very much demand for changes and plugin works with latest Piwik/Matomo version for my best knowledge :)

Do you mind sharing why are you asking? Is something broken or you could use some changes?
If there is some extra value to be delivered with this plugin, please feel free to share your ideas and it can surely be put to action.

Best,
Mike

**Comment by Makkmetp** [comment]
Hello @mgazdzik ,

thanks for your responds. 

I have installed the plugin for a customer and they are happy with it. 
One of the things I think could add some extra value is the possibility to select which website can use the plugin and which are not. Or perhaps users only with "Write" acces can use the plugin. 
Is that an option to put in the plugin?

Regards,
Peter

**Comment by mgazdzik** [comment]
Hi,
  I think that restricting creating shortcodes only to users with more than "read only" access makes totally sense, thank you very much for that suggestion :) 
I will try to put together a change during following days and hopefully release a new version of plugin so that you can update it for your client :)
I will get back to you in this thread once it's done and released.

Best,
Mike

**Comment by Makkmetp** [comment]
Hi Mike,

that would be great. Thank you allready.

Best,
Peter

**Comment by Makkmetp** [comment]
Hi Mike,  
have you allready take a look to change the permissions to create a short URL for users with Write access?

Regards,
Peter

**Comment by mgazdzik** [comment]
Hi Peter, 
Please accept my huge apologies for getting back to you so late, but simply put I couldn't find time for that change before. Right now build is running for code change that I believe would do the trick
- remove menu item for generating shortcode for users with no admin privilege
- block in-row action on pages report.

If all goes well within few hours new plugin version should be ready on production. 
Hope you still can use the plugin!

Best,
Mike

**Comment by Makkmetp** [comment]
Hi Mike,
No problem. 
I did some tests with the new plugin and found some issues:

- As a user with Admin privilege I can't create a new shortcode. When I hit the button Generate Shortcode I receive the message "_You can't access this resource as it requires a 'superuser' access._"

- When I open the reports External Shortcode Usage and Most Shortened External Pages I get the message "_Error: The parameter 'idSite=' is missing from the request._" and the login page of Matomo. 

Regards,
Peter

**Comment by mgazdzik** [comment]
Hi Peter,
 Thanks for testing this and apologies for regression. I believe I have found the issue and fixed it.
As for second problem unfortunately I was not able to reproduce it - could you please check this with the 1.1.1 version? It has been just released to master.
Thanks in advance!

Best,
Mike

**Comment by Makkmetp** [comment]
Hi Mike,
my apologies for my late reaction. But I tested the new plugin and still had some issues. 
These were:
- when a user has admin rights and wants to create a shortcode by pushing on the button, the error message : You can't access this resource as it requires a 'superuser' access. is shown.
- when I select the reports I get all kind of messages. For the reports Shortcode Usage Report and Most Shortened Pages the message Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your administrator for assistance.  is shown.
For the other two reports the message Error: The parameter 'idSite=' is missing from the request. is shown.

I checked my installation on the NGINX server and all looked correct. 
Perhaps you have some ideas what is going wrong. 

Best,
Peter
