### ISSUE TITLE
404 pages within the doc

### ISSUE THREAD

**Issue by ghost** [mgazdzik/plugin-ShortcodeTracker#33]
On the setup page the two links to nginx config and apache are broken.
Real links are:
https://github.com/mgazdzik/plugin-ShortcodeTracker/blob/master/docs/nginx_config.txt
https://github.com/mgazdzik/plugin-ShortcodeTracker/blob/master/docs/apache_config.txt

**Comment by mgazdzik** [comment]
Thanks @NanorPiwik for reporting that! Indeed, links were broken on marketplace. I've just released a bugfix version and links are now operating properly.
Cheers!
