### ISSUE TITLE
Error when opening reports without data

### ISSUE THREAD

**Issue by funkdoobiest** [mgazdzik/plugin-ShortcodeTracker#36]
Hi,

when I open usage report for a date range before shortcode was installed / without data following error occurs (500er):

```
A fatal error occurred
The following error just broke Matomo (v3.10.0):

Call to a member function getIdSubDataTable() on boolean
in /var/www/matomo/plugins/ShortcodeTracker/API.php line 362
```         
Ajax request url: 

https://analytics.xxx.com/index.php?module=ShortcodeTracker&action=getShortcodeUsageReport&idSite=1&period=month&date=2019-06-13&showtitle=1&random=6234

**Comment by yarick123** [comment]
Hi, we are experiencing the same problem :(

**Comment by mgazdzik** [comment]
Hi guys, thanks for reporting that issue. 
I will try to find that error and fix, but to be honest I cannot promise any specific date for that more than "in coming 2 weeks", as my day job is pretty absorbing. 
If you have such possibility to suggest a solution I'd be more than happy to help you merge that into the plugin.

Best,
Mike
