### ISSUE TITLE
Make plugin compatible with Matomo 4

### ISSUE THREAD

**Issue by Findus23** [mgazdzik/plugin-ShortcodeTracker#37]
Hi, hope you are doing well!

Matomo 4 is progressing steadily and it would be great if this plugin was also [available for it](https://matomo4-plugins.lw1.at/).

[Migrating the plugin](https://matomo.org/blog/2020/08/matomo4-make-your-plugin-compatible-now/) should be pretty simple as there were not many breaking changes.

You can find the migration guide here: https://developer.matomo.org/guides/migrate-matomo-3-to-4

It boils down to:
- update your dev environment to 4.x-dev
- update your plugin.json (new major version of the plugin and require `>=4.0.0-b1,<5.0.0-b1`)
- check that everything still works fine
- commit this to a new branch (e.g. `4.x-dev`) and make this branch the default in the github settings
- tag and push a new release to publish it to the marketplace

If you later fix a bug and also want to backport it to the 3.x plugin, you can cherry-pick the commit to the old branch, release a new version (lower than the one for 4.x) and publish it and 3.x users should get this update.

If you have questions about anything, just ask me!

While the plugin is a bit more complex, I don't think it needs many changes to work with Matomo 4 as few related things changed. Contact me, if I should help with testing.

**Comment by mgazdzik** [comment]
Hi @Findus23 , thanks for reaching out and apologies for taking so long to respond - but finally updated version of plugin is uploaded to repo and published to marketplace! :) The update turned out to be way easier that it seemed it would be.

Cheers and keep up the good work with platform :)
