### ISSUE TITLE
External events

### ISSUE THREAD

**Issue by LittleJohnAU** [mgazdzik/plugin-ShortcodeTracker#38]
I have matomo set up on the subdomain mat.mydomain.com and I have another subdomain for my shortening service at p.mydomain.com

I am passing the visitor id and referrer to the url on my domain, as session variables, and using the php tracking client to record the event:

$matomoTracker->doTrackEvent('shortcode', 'redirect', $shortCode);

It's recording the event and assigning it to the user just fine, but there's nothing showing up in the usage report.

![shortcode](https://user-images.githubusercontent.com/70997252/92557757-44c2bb80-f2b0-11ea-82f7-6e7f88653763.jpg)

I'm new to Matomo and a bit stumped as to what I can do to make this work. Any suggestions?

**Comment by mgazdzik** [comment]
Hello John, thanks for reaching out!
I've checked the case you described and for me it was matter of running the archiving process for the data to pop up in the report.
My guess is that your instance hasn't yet processed all the reports (aka the archiving process) - maybe this article will be helpful with setting it up  https://matomo.org/docs/setup-auto-archiving/ 
Alternatively you can also set the archiving to run every time you refresh a report in the browser, but this is suitable only for rather smaller instances (go to Settings -> [System] General Settings -> there you'll see first section "Archiving settings" - thats where you can change it).

Hope it helps, if not - please feel free to let me know, I'll try to figure out how to solve it for you :)

Cheers,
Michael

**Comment by LittleJohnAU** [comment]
Hi Michael,
I set up the cron job when I installed and I just changed it to refresh the report in the browser to see if that would work, but there's still nothing showing in the usage report. Could it be that there's only two events with short codes recorded?

I've created a repository you can take a look at and see what you think. https://github.com/LittleJohnAU/matomo-redirector

**Comment by mgazdzik** [comment]
Hi John,
 Thank you, it gives me slightly more insight into what are you working with. 
Three questions that come up to my mind are
1 - are you using this plugin in unchanged form? I'm not sure why your upload seems to contain somewhat duplicated logic of what the plugin does on it's own?
2 - if events seem to be showing up in Visitor Log, they should also be visible in Behaviour -> Events report - can you please check if they show up?
3 - Also last but not least - can you maybe hint me where exactly are you checking the shortcode usages (i.e. the report name, maybe some screenshot would be useful)

**Comment by LittleJohnAU** [comment]
Hi Michael,
Haven't changed a thing with the plugin. It seems duplicated, because the repository is all the files I have on the subdomain that Matomo is not on.

They are showing up in the Behaviour -> Events reports.
![events](https://user-images.githubusercontent.com/70997252/92713423-4e2a5180-f39e-11ea-9d03-7b3d049aecd9.jpg)

I get an error now, when I go to the usage report
![shortcode](https://user-images.githubusercontent.com/70997252/92713443-54203280-f39e-11ea-829a-79be032edbad.jpg)

They are showing up in the visitor log. The only problem I'm having, is with the usage report. It's not a big drama, would just be good to get it all working.

**Comment by LittleJohnAU** [comment]
Updated the readme, as I forgot to put in the .htaccess code
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([a-zA-Z0-9]+)/?$ index.php?c=$1 [L] 
</IfModule>
```

**Comment by mgazdzik** [comment]
Ok, so the change in .htaccess should be the only thing that you change in the webserver of your website, the tracker etc are not necessary, plugin takes care of that.

As for the reporting did you maybe configure the external redirection site? If not, it could be the missing piece of puzzle - here's the section in plugin readme https://github.com/mgazdzik/plugin-ShortcodeTracker#external-redirects-tracking 

Also it would be useful if you could get grip of the PHP error logs that show up when trying to display the report, as the message on the screenshot is quite generic.

**Comment by LittleJohnAU** [comment]
I found the problem. In the file ShortcodeTracker/ShortcodeTracker.php, you have the value for the constant spelled wrong
```
const REDIRECT_EVENT_CATEGORY = 'shordcode';
```
I've changed it to
```
const REDIRECT_EVENT_CATEGORY = 'shortcode';
```
That's got it working now

**Comment by LittleJohnAU** [comment]
Here's the folder structure on the server, to give you an idea of how it works. Neither the root domain or redirection subdomain have access to matomo directly. They both use the [PHP tracking client](https://github.com/matomo-org/matomo-php-tracker)
![folders](https://user-images.githubusercontent.com/70997252/92758609-3e2c6500-f3d2-11ea-8902-85617262dcfc.jpg)
I'd like to thank you Michael, for creating this plugin. It's just what I needed. Thanks for your patience and assistance in resolving this issue.

**Comment by mgazdzik** [comment]
Hi John, thank you a lot for pointing that problem! I will check its impact and release an update version.
Also just for clarity - there's no need to use Matomo PHP tracker on your website. 
The whole concept of tracking is based on following chain:
1) make request to webserver with shortcode
2) shortcode is translated  (by .htaccess or apache config)  and redirected to the Shortcode Plugin API
3) Plugin API takes care of calling proper tracking methods
4) Therefore events should be recorded properly

However I'm glad that one way or another you found way to set it up for your usage :) Hope it'll serve you well!

Having said above - I'll close this issue once I push fix to master :) 
Thank you too for effort in finding the fix!

Cheers,
Michael

**Comment by LittleJohnAU** [comment]
No worries Michael. Glad I could help a little with debugging.

The reason I created this, was partly for security, as it keeps people away from my Matomo site, but mainly so my short url is as short as possible. The subdomain is only one letter (p). Also, I didn't want to do a double redirect, in that it redirects to the matomo subdomain and then again to the url for the short code, Plus, I output a nice looking page with an error, if there's no short code supplied or it doesn't exist. I'm going to add a 404 header if the code doesn't match.

**Comment by LittleJohnAU** [comment]
Quick note: If you change the spelling and people have been using it, when they update, previous records won't show up, as they were recorded with the category as shordcode, not shortcode. I've added a note to the readme, to let people know to check it and change the spelling if they use my script.

> Check the ShortcodeTracker plugin file -> **ShortcodeTracker/ShortcodeTracker.php** for the following constant:
```php
const REDIRECT_EVENT_CATEGORY
```
> If the value is `'shordcode'` change it to `'shortcode'` or the reports will not work. NOTE: If you have been using the Shortcode Tracker plugin prior to this and the category is mispelled, changing it will cause you to lose that data. If this is an issue, then change the spelling in index.php `$matomoTracker->doTrackEvent('shortcode', 'redirect', $shortCode);` to `$matomoTracker->doTrackEvent('shordcode', 'redirect', $shortCode);`
