### ISSUE TITLE
Additional URL with Docker and Traefik

### ISSUE THREAD

**Issue by WuGGu** [mgazdzik/plugin-ShortcodeTracker#39]
Hi,

first of all: thank you for the plugin. 
My setup is a docker server with Matomo and Traefik. 
https://omo.example.com <-- url to Matomo
And now I want to use a short url like: xmpl.com/5239gd <--
I use Traefik as a Reverse Proxy and generator for my Let's Encrypt certs. 
Do I also have to route the xmpl.com URL to Matomo? Or can I avoid this. Do you have experiences with Traefik instead of Ngnix?

thanks

**Comment by mgazdzik** [comment]
Hi @WuGGu !

First thing - thank you very much for kind words and I'm very happy that you found my plugin useful :)

As for your question - unfortunately I don't have any knowledge of Traefik, but here's basically what you need to do:
1. capture requests to https://xmpl.com/{shortcode} and force a redirect
2. redirect should lead to https://omo.example.com/index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code={shortcode} 
3. this in consequence will redirect your user to proper URL stored under given {shortcode}

If you take a look at example htaccess rewrites [[here](https://github.com/mgazdzik/plugin-ShortcodeTracker/blob/master/docs/apache_config.txt)] you may be able to figure it out. 
Generally you should ensure in your redirect rules that none of other working pages on https://xmpl.com domain (like home/aboutme/contact/etc.) are caught in this rule, so you can play with shortcode length.

Hope this explanation makes it a bit easier to figure out, good luck with finishing it!

If you have any other questions please feel free to reach me out further :)

Best,
Mike
