### ISSUE TITLE
Shortcode generation for users and external site tracking are not fixed for Matomo3

### ISSUE THREAD

**Issue by khassad** [mgazdzik/plugin-ShortcodeTracker#43]
Hi, the recent fixes listed in #41 are only valid for Matomo 4.
Some of us around still uses Matomo 3 so I thought would be great to backport those important fixes to continue to support Matomo 3.

**Comment by mgazdzik** [comment]
I'm sorry @khassad but I simply cannot maintain two compatibility lines of the plugin, so my recommendation is to migrate to latest version.
