### ISSUE TITLE
Unclear about the "Shortener URL" field in admin

### ISSUE THREAD

**Issue by Razique** [mgazdzik/plugin-ShortcodeTracker#48]
Hi,
the documentation states that:

 >If enabled, the value will be automatically refreshed depending on the specified interval

But there's no explanation about what this field does, only what happens when filled. 
Cheers :)

<img width="1343" alt="Screenshot 2021-11-07 at 15 15 56" src="https://user-images.githubusercontent.com/1027278/140665534-d9ab391b-45f4-4af4-8a12-e35bc2df6d20.png">

**Comment by realPilotfish** [comment]
This setting seems to determine the string, that ist prepended to the generated shortcode.
I.e. _http://myshort.com/_ leads to something like http://myshort.com/78fd21 when generating a shortcode.

**Comment by Razique** [comment]
Thanks, and what is the purpose of that setting?

**Comment by froger-me** [comment]
Determining the path where the actual rewrite is to be made - hitting the http://myshort.com/78fd21 URL must trigger the rewrite rules doing the redirection - see files in https://github.com/mgazdzik/plugin-ShortcodeTracker/tree/master/docs,  `Piwik\Plugins\ShortcodeTracker\API::performRedirectForShortcode` and `Piwik\Plugins\ShortcodeTracker\API::generateShortenedUrl` source code (particularly this bit in the latter: `return $baseUrl . $response;`) for more details.

But yeah, the field's description is entirely irrelevant.

**Comment by Razique** [comment]
To make sure that I understand, this allows you to override the base URL?
So suppose I have another redirection service or a CNAME, I can put the base domain there, e.g. `https://my.redirect.service` and the plug-in will use that value instead of defaulting to the default hostname?

**Comment by froger-me** [comment]
That's my understanding, yes, but I could be wrong - and, searching the source code for `ShortcodeTracker::SHORTENER_URL_SETTING`:

- it is used to override the referrer during tracking
- it is used in a purely cosmetic manner in the result popup

**Comment by Razique** [comment]
Excellent, thanks @froger-me we can go ahead and mark it as resolved.
