### ISSUE TITLE
 Does not seem to work with WordPress

### ISSUE THREAD

**Issue by froger-me** [mgazdzik/plugin-ShortcodeTracker#50]
No matter where the .htaccess recommend rules are pasted, the page ends up in a 404.

It looks like the following rule:

```
RewriteRule ^([a-zA-Z0-9]{6})$ /index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code=$1 [L]
```

should instead be something like (not perfect because path is harcoded):

```
RewriteRule ^([a-zA-Z0-9]{6})$ /wp-content/plugins/matomo/app/index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code=$1 [L]
```

But then when testing this, the browser shows:

```xml
<result>
    <error message="Token is not valid."/>
</result>
```

Any advice would be very appreciated.

**Comment by froger-me** [comment]
I'm not sure how clean or secure that is because I'm not very familiar with dev for Matomo (specially in terms of security implication - I'm under the impression that we **do not** want to check for access right when performing shortcode redirection?), but here's my solution so far:

1 - Use a different rule in `.htaccess`

```
# BEGIN Matomo Short URL put in .htaccsss
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f  
RewriteCond %{REQUEST_FILENAME} !-d
RewriteBase /
RewriteRule ^([a-zA-Z0-9]{6})$ /wp-content/plugins/matomo/app/index.php?module=ShortcodeTracker&action=doRedirect&code=$1 [L]
</IfModule>
# END Matomo Short URL
```

2 - Adding a method `Piwik\Plugins\ShortcodeTracker\Controller::doRedirect`

```php
/**
 * Piwik - free/libre analytics platform
 *
 * @link    http://piwik.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Piwik\Plugins\ShortcodeTracker;

use Piwik\Common;
use Piwik\Plugins\ShortcodeTracker\Component\ShortcodeValidator;
use Piwik\View;


/**
 * @codeCoverageIgnore
 */
class Controller extends \Piwik\Plugin\Controller
{
    public function showShortcodePopup()
    {
        $shortcode = Common::getRequestVar('shortcode');
        $pluginSettings = new SystemSettings();
        $baseUrl = $pluginSettings->getSlashedSetting(ShortcodeTracker::SHORTENER_URL_SETTING);

        $view = new View('@ShortcodeTracker/singleShortcode');
        $codeValidator = new ShortcodeValidator();
        if ($codeValidator->validate($shortcode) === true) {
            $view->header = 'ShortcodeTracker_generated_shortcode_is';
            $view->text = $baseUrl . $shortcode;
            $view->containerClass = 'alert-success';
        } else {
            $view->header = 'ShortcodeTracker_unable_to_generate_shortcode';
            $view->text = 'ShortcodeTracker_provide_valid_url';
            $view->containerClass = 'alert-warning';
        }

        return $view->render();
    }

    // THIS IS THE ADDED BIT
    public function doRedirect()
    {
        API::getInstance()->performRedirectForShortcode(Common::getRequestVar('code'));
    }
}
```

Please advise - if the plugin is meant to be available for WordPress, I'm willing to help and investigate, but if not, it'd be better to remove it from the marketplace.

**Comment by Ozzie76** [comment]
Ran into the same issue on an Apache server.

1. use this addition to the .htaccess file: https://github.com/mgazdzik/plugin-ShortcodeTracker/blob/master/docs/apache_config.txt
There are other, older codes out there that are either specific to the Wordpress "Matomo" plugin, or the "WP-piwik" plugin.
2. the code by mgazdzik is pointing to a Matomo instance that's running on the same server as the Wordpress instance, as is the setup when using the Wordpress "Matomo" plugin. Mine has it's own server and url and got it working with the following change.
From:  RewriteRule ^([a-zA-Z0-9]{6})$ /index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code=$1 [L]
To: RewriteRule ^([a-zA-Z0-9]{6})$ http://[YOUR SERVER URL]/index.php?module=API&method=ShortcodeTracker.performRedirectForShortcode&code=$1 [L]

**Comment by mgazdzik** [comment]
Closing the issue for now due to it's age, please reopen if the problem still exists.
