### ISSUE TITLE
There is no data for this report

### ISSUE THREAD

**Issue by james-green-affinity** [mgazdzik/plugin-ShortcodeTracker#53]
I have configured the plugin on my Matomo instance and Nginx. I can successfully generate short links and get redirected as expected. However when I review the reports I get "There is no data for this report."

![image](https://user-images.githubusercontent.com/91469943/174776092-c99ae59c-c7e3-49ae-9ccf-5920d3f8a723.png)

**Comment by mgazdzik** [comment]
Hello @james-green-affinity , thanks for the reporting.
Two things I'd check in the first place are:
- is your archiving process set up properly? does it run and are there any errors in archiving?
- also in the screenshot provided I can see that you display data for 2022.06.20 which I assume is "yesterday" (default setting in Matomo) and if you made redirects today you'd need to change the date to 2022.06.21.
Also you should be able to view the redirect events in the Visitor Log report to confirm if they're being tracked.

Please let me know if any of this helps?

Cheers!

**Comment by james-green-affinity** [comment]
It was the incorrect date that was the problem thanks
