### ISSUE TITLE
Shortcode api

### ISSUE THREAD

**Issue by plegault3397** [mgazdzik/plugin-ShortcodeTracker#54]
Is it possible to access the usage report through matomo api?

**Comment by mgazdzik** [comment]
Yes, this plugin offers standard API access pretty much as every other plugin in Matomo :)
You can find the list of methods and params when you go to settings -> platform -> API and then click on the plugin name or  scroll down till you see it. 

![Zrzut ekranu 2022-06-28 o 07 14 07](https://user-images.githubusercontent.com/3390652/176098149-a910bd77-2445-4238-8286-d499d4e65076.png)

**Comment by plegault3397** [comment]
Great,
Thanks for the help, this is perfect
