### ISSUE TITLE
The shortcode usage is not showing up in the report.

### ISSUE THREAD

**Issue by plegault3397** [mgazdzik/plugin-ShortcodeTracker#55]
I use the shortcode link and then I select "Shortcode usage report"  period=week&date=today, I get the message below.

(It looks like reports for this period have not been processed yet. Do you want to see what's happening now? Check out the [Visits log] or choose a different date period until the reports are generated.)

How is the api report generated?

**Comment by mgazdzik** [comment]
The reports are generated during the archiving process so as per error message please ensure that archiving process has completed between moment of tracking a shortcode redirect and time when you query the API endpoint, or change the archiving settings to enable browser triggered processing.

**Comment by plegault3397** [comment]
Thanks
