### ISSUE TITLE
Shortcode api date range

### ISSUE THREAD

**Issue by plegault3397** [mgazdzik/plugin-ShortcodeTracker#57]
I have been running a script using date range, it was working fine and suddenly it stopped working. Not sure if it was an update or what happened. I was using it to get x number of months with start of month end of month month variables in a loop. I was able to change it to use month and start of month date.

**Comment by mgazdzik** [comment]
@plegault3397 the plugin hasn't been updated in quite a while so unfortunately I cannot help with the problem you describe in any way. I would suggest checking out error logs of archiving process to find out if there is any any php/server error.

**Comment by plegault3397** [comment]
PHP 7.4 is going EOL and I upgraded to PHP 8.1, This is the only change I made.

**Comment by mgazdzik** [comment]
@plegault3397 I've just updated my php to 8.1 and plugin still seems to be working fine. can you please provide more details about how do you use the plugin, i.e. what kind of script are you running and are you getting any php/mysql errors?
