### ISSUE TITLE
Compatibility issue when generating reports

### ISSUE THREAD

**Issue by vccs** [mgazdzik/plugin-ShortcodeTracker#59]
May be due to the new Matomo DB structure, when checking SC in the reports options;

`Matomo encountered an error: Call to undefined method Piwik\DataTable\Map::getRowFromLabel() (which lead to: Zend_Session is currently marked as read-only.)` - When downloading report

When sending Report (UI info): Call to undefined method Piwik\DataTable\Map::getRowFromLabel()

Hoping can be replicated by others, thank you.

**Comment by mgazdzik** [comment]
Hi @vccs , can you please share what version of Matomo are you using? 
On my instance I'm running 4.12.3 and I'm capable of using all reports for the plugin without errors.

**Comment by vccs** [comment]
Ok I guess it's just me then sorry. I'll dive deeper thanks! (4.12.3)
