### ISSUE TITLE
Plug-in not compatible with Matomo 5

### ISSUE THREAD

**Issue by Razique** [mgazdzik/plugin-ShortcodeTracker#62]
Hi,
I have upgraded my Matomo instance to version 5 this morning, and I discovered that the plug-in is not compatible:
```
ShortcodeTracker requires Matomo <5.0.0-b1. 
```

thank you.

**Comment by mgazdzik** [comment]
Hi @Razique , I'm happy to let you know that thanks to Matomo community support I was just able to release an updated version of the plugin that should work fine with the latest Matomo.
Cheers!

**Comment by Razique** [comment]
Most excellent, thank you so much! :)
